name: homee_3DGS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.8
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - scipy=1.7.3
  - faiss-gpu
  - tqdm
  - trimesh
  - opencv
  - numba
  - pyquaternion
  - setuptools=69.5.1
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - git+https://github.com/NVlabs/tiny-cuda-nn/@v1.6#subdirectory=bindings/torch
